# Site settings
author: Daniel Lee
title: reBoost
header-img: img/home-bg.png
email: leedc@me.com
copyright_name: Daniel Lee
description: > # this means to ignore newlines until "baseurl:"
  Follow my journey to boost my career to the next level
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  leedc0

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
